### ISSUE TITLE
More Results button fails

### ISSUE THREAD

**Issue by MilesParker** [boundstate/hgweb-boundstate-theme#10]
One final minor issue (still fails on latest hg version):

1. Search for file or user.
2. Click "More Results"

I get:

Whoops!
An error occurred while processing your request:

no such method: search

**Comment by jan-dx** [comment]
If you change line #51 of search.tmpl, from ```
<a class="btn" href="{url}search/{morevars%urlparameter}#more" name="more">More Results</a>
``` to ```
<a class="btn" href="{url}log{morevars%urlparameter}#more" name="more">More Results</a>
``` problem will be solved.

Regards,
Nazim Can.
