### ISSUE TITLE
Theme doesn't work

### ISSUE THREAD

**Issue by maxirobaina** [boundstate/hgweb-boundstate-theme#12]
Hi,

I can't make that the theme works for me.
I follow the instructions to install from readme into master branch [1] but it doesn't work.

I'm running Mercurial Distributed SCM (version 3.0.1), Python 2.7.3 and Ubuntu Server 14.04 64 bits

What am I missing to configure?

[1] https://github.com/boundstate/hgweb-boundstate-theme/blob/master/README.md#installation

**Comment by mikejpeters** [comment]
What exactly happens? Do you get an error message of any kind? Can you provide me the `[web]` section of your `hgweb.config` file?

**Comment by maxirobaina** [comment]
Hi @mikejpeters 

The issue is that nothing happen, that is to say no error occurred, It just show me the default theme.
My config is:

[web]
base_url = /hg
template = /home/vikingo/public_html/mercurial/hgweb-boundstate-theme
#style = gitweb
style = boundstate
encoding = UTF-8
....

In hgweb-boundstate-theme folder I have:

README.md  boundstate   screenshot.png  static

**Comment by mikejpeters** [comment]
Please change `template = ...` to `templates = ...` (missing an "s")

The reason we do that is to tell Mercurial to look in our custom directory for all templates, which is a simpler way to install this template compared to copying both the *boundstate* and *static* folders into the default templates directory.

**Comment by maxirobaina** [comment]
Ouch!
It works ok now.
Thanks a lot.
